# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-postcss

# jekyll-seo-tag configuration
author: ""
url: ""
title: "FinOps Foundation - Collaborative, Real-Time Cloud Financial Management"
description: "Delivering expertise, and inspiration for and by FinOps leaders and practitioners — all aimed at helping members become better at cloud financial management."
twitter:
  username: ""
  card: ""
logo: "path/to/image"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - netlify.toml
  - bin
  - .gitignore
  - vendor
permalink: pretty

collections:
  stories:
    output: true

include: [_redirects]
